### ISSUE TITLE
Button cannot wrap around an image

### ISSUE THREAD

**Issue by Jsnncls** [Saadmairaj/tkmacosx#37]
Buttons that has an image will always have a buffer around said image. If the "width" and "height" attributes are used, the button would disappear completely. 

**Steps to reproduce the image buffer problem:**
1. Create a normal button with a .png file as the image.
`        
image_2= PhotoImage(file = insert image file here.png, height=48, width=55)
self.two    = Button(root, image=self.image_2, relief=FLAT, bg='#a9a9a9', command=lambda:self.addNum(num=2), bd=0, highlightthickness=0, borderless=1)
self.two.grid(row=5, column=2)`

**Steps to reproduce the disappearing button problem:**
1. Create a normal button with a .png file as the image, set the width and height to any value.
`        
image_3= PhotoImage(file = insert image file here.png, height=48, width=55)
self.three  = Button(root, image=self.image_3, relief=FLAT, bg='#a9a9a9',command=lambda:self.addNum(num=3), width=100, height=200)
self.three.grid(row=5, column=3)
`

**Expected behavior**
The button wraps around the border of the image, making the button just as big as the image used, not bigger and creating a buffer around the image.

**Screenshots**
![Screen Shot 2022-01-07 at 10 14 45](https://user-images.githubusercontent.com/97269196/148485621-55b747e6-ed5f-4c55-b5b6-1e0b615ddd7d.png)
Image 1: Buffer around the image

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version Big Sur 11.6.1

**Comment by Saadmairaj** [comment]
Hi Jsnncls! Thanks for mentioning the `width / height` issue and It will be fixed in the next update hopefully. 

However, **_"button wraps around the border of the image"_** is not an issue as the tkmacosx button simulates ttk button, not the actual Tkinter button but it can be set by giving some negative padding.

For some reason for width and height, it is not registering them initially for images but you can get away by defining after Button is created like so

```python
from tkinter import Tk, PhotoImage
import tkmacosx as tkm

root = Tk()
image = PhotoImage(file="unnamed.png", width=50, height=50)
root.tmp_image = image
b1 = tkm.Button(root, image=image)
b1.configure(width=100, height=200)
b1.pack()
root.mainloop()
```
<img width="248" alt="image" src="https://user-images.githubusercontent.com/46227224/148641247-ca7a7d65-f608-4d31-b11c-31fe0524efd2.png">

And for negative padding, you can do the following
```python
from tkinter import Tk, PhotoImage
import tkmacosx as tkm

root = Tk()
image = PhotoImage(file="unnamed.png", width=50, height=50)
root.tmp_image = image
b1 = tkm.Button(root, image=image, padx=-15, pady=-1)
b1.pack()
root.mainloop()
```
<img width="198" alt="image" src="https://user-images.githubusercontent.com/46227224/148641273-451f5d2b-0f36-452c-9d78-8bb91221d5c5.png">

_Original Image used in the above example_
![unnamed](https://user-images.githubusercontent.com/46227224/148641375-4585df3b-2b66-4c78-b83b-4562fd981596.png)

**Comment by Jsnncls** [comment]
Thanks a lot!
